<?php

use Sitchco\Integration\Wordpress\Cleanup;
use Sitchco\Parent\ContentPartial\ContentPartialModule;
use Sitchco\Parent\ContentPartialBlock\ContentPartialBlockModule;
use Sitchco\Parent\PageOrder\PageOrderModule;
use Sitchco\Parent\SiteFooter\SiteFooterModule;
use Sitchco\Parent\SiteHeader\SiteHeaderModule;
use Sitchco\Parent\Theme;

return [
    'modules' => [
        Cleanup::class => [
            'disableGutenbergStyles' => false,
        ],
        ContentPartialModule::class,
        ContentPartialBlockModule::class,
        SiteHeaderModule::class,
        SiteFooterModule::class,
        PageOrderModule::class,
        Theme::class
    ],
    'blocks' => true, /*[
        'core/audio',
        'core/block',
    ],*/
    'core_block_ref' => [
        'core/archives',
        'core/audio',
        'core/avatar',
        'core/block',
        'core/button',
        'core/buttons',
        'core/calendar',
        'core/categories',
        'core/code',
        'core/column',
        'core/columns',
        'core/comment-author-name',
        'core/comment-content',
        'core/comment-date',
        'core/comment-edit-link',
        'core/comment-reply-link',
        'core/comment-template',
        'core/comments-pagination-next',
        'core/comments-pagination-numbers',
        'core/comments-pagination-previous',
        'core/comments-pagination',
        'core/comments-title',
        'core/comments',
        'core/cover',
        'core/details',
        'core/embed',
        'core/file',
        'core/footnotes',
        'core/freeform',
        'core/gallery',
        'core/group',
        'core/heading',
        'core/home-link',
        'core/html',
        'core/image',
        'core/latest-comments',
        'core/latest-posts',
        'core/legacy-widget',
        'core/list-item',
        'core/list',
        'core/loginout',
        'core/media-text',
        'core/missing',
        'core/more',
        'core/navigation-link',
        'core/navigation-submenu',
        'core/navigation',
        'core/nextpage',
        'core/page-list-item',
        'core/page-list',
        'core/paragraph',
        'core/pattern',
        'core/post-author-biography',
        'core/post-author-name',
        'core/post-author',
        'core/post-comments-form',
        'core/post-comments',
        'core/post-content',
        'core/post-date',
        'core/post-excerpt',
        'core/post-featured-image',
        'core/post-navigation-link',
        'core/post-template',
        'core/post-terms',
        'core/post-title',
        'core/preformatted',
        'core/pullquote',
        'core/query-no-results',
        'core/query-pagination-next',
        'core/query-pagination-numbers',
        'core/query-pagination-previous',
        'core/query-pagination',
        'core/query-title',
        'core/query',
        'core/quote',
        'core/read-more',
        'core/rss',
        'core/search',
        'core/separator',
        'core/shortcode',
        'core/site-logo',
        'core/site-tagline',
        'core/site-title',
        'core/social-link',
        'core/social-links',
        'core/spacer',
        'core/table',
        'core/tag-cloud',
        'core/template-part',
        'core/term-description',
        'core/text-columns',
        'core/verse',
        'core/video',
        'core/widget-group',
    ],
];
