<?php

use Sitchco\Integration\Wordpress\Cleanup;
use Sitchco\Parent\ContentPartial\ContentPartialModule;
use Sitchco\Parent\ContentPartial\ContentPartialPost;
use Sitchco\Parent\ContentPartialBlock\ContentPartialBlockModule;
use Sitchco\Parent\PageOrder\PageOrderModule;
use Sitchco\Parent\SiteFooter\SiteFooterModule;
use Sitchco\Parent\SiteHeader\SiteHeaderModule;
use Sitchco\Parent\Theme;

return [
    'modules' => [
        Cleanup::class => [
            'disableGutenbergStyles' => false,
        ],
        ContentPartialModule::class,
        ContentPartialBlockModule::class,
        SiteHeaderModule::class,
        SiteFooterModule::class,
        PageOrderModule::class,
        Theme::class,
    ],
    'disallowedBlocks' => [
        'core/comment-template',
        'variation;core/embed;twitter',
        'variation;core/embed;facebook',
        'variation;core/embed;instagram',
        'variation;core/embed;wordpress',
        'variation;core/embed;soundcloud',
        'variation;core/embed;spotify',
        'variation;core/embed;flickr',
        'variation;core/embed;animoto',
        'variation;core/embed;cloudup',
        'variation;core/embed;collegehumor',
        'variation;core/embed;crowdsignal',
        'variation;core/embed;dailymotion',
        'variation;core/embed;imgur',
        'variation;core/embed;issuu',
        'variation;core/embed;kickstarter',
        'variation;core/embed;mixcloud',
        'variation;core/embed;pocket-casts',
        'variation;core/embed;reddit',
        'variation;core/embed;reverbnation',
        'variation;core/embed;screencast',
        'variation;core/embed;scribd',
        'variation;core/embed;smugmug',
        'variation;core/embed;speaker-deck',
        'variation;core/embed;tiktok',
        'variation;core/embed;ted',
        'variation;core/embed;tumblr',
        'variation;core/embed;videopress',
        'variation;core/embed;wordpress-tv',
        'variation;core/embed;amazon-kindle',
        'variation;core/embed;pinterest',
        'variation;core/embed;wolfram-cloud',
        'variation;core/embed;bluesky',
        'core/post-author',
        'core/post-author-biography',
        'core/post-author-name',
        'core/avatar',
        'core/comment-author-name',
        'core/comment-content',
        'core/comment-date',
        'core/comment-edit-link',
        'core/comment-reply-link',
        'core/comments',
        'core/post-comments-form',
        'core/comments-pagination-next',
        'core/comments-pagination-numbers',
        'core/comments-pagination',
        'core/comments-pagination-previous',
        'core/comments-title',
        'core/post-content',
        'core/post-date',
        'core/post-excerpt',
        'core/post-featured-image',
        'core/loginout',
        'core/query-pagination-next',
        'core/query-no-results',
        'core/query-pagination-numbers',
        'core/query-pagination',
        'core/pattern',
        'core/post-navigation-link',
        'core/post-template',
        'core/post-terms',
        'core/query-pagination-previous',
        'core/query',
        'core/query-title',
        'core/template-part',
        'core/term-description',
        'core/post-title',
        'core/latest-comments',
        'core/latest-posts',
        'core/rss',
        'core/search',
        'core/tag-cloud',
        'core/categories',
        'core/navigation' => [
            'allowPostType' => [
                ContentPartialPost::POST_TYPE
            ]
        ],
    ],
];
